### ISSUE TITLE
Move the Home icon to the left side of the Navbar

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/hunajaholisti-website#21]
Move the Home icon (HHlogo.jpg) to the left side of the Navbar, leaving all the other links to the right. Make sure that in mobile view it does not change it's position.

**Comment by Utkarsh3010** [comment]
I will Like to Contribute and Make the changes as per your requirement . if you allow me to do so

**Comment by nikohoffren** [comment]
> I will Like to Contribute and Make the changes as per your requirement . if you allow me to do so

Sure, go ahead.

**Comment by nikohoffren** [comment]
> I will Like to Contribute and Make the changes as per your requirement . if you allow me to do so

Are you still working on this issue? If not, i will fix it.

**Comment by Utkarsh3010** [comment]
Yes I am Working.

**Comment by Utkarsh3010** [comment]
I am Extremely sorry But It seems like I am unable to Fix it

**Comment by nikohoffren** [comment]
> I am Extremely sorry But It seems like I am unable to Fix it

No problem, i have also many other issues on my repos if you like to try them.
