### ISSUE TITLE
Switch product placement

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/hunajaholisti-website#32]
Switch the product placement between `Big Adopt a Hive` and `Small Adopt a Hive` products in Products.tsx.

**Comment by Nkiriobasi** [comment]
I’ll fix this.

**Comment by nikohoffren** [comment]
> I’ll fix this.

Sure, go ahead.

**Comment by Nkiriobasi** [comment]
Please, help throw more light on this. Thanks

**Comment by nikohoffren** [comment]
> Please, help throw more light on this. Thanks

Of course! So in Products.tsx, the `Big adopt a Hive` product has to be in `Small adopt a Hive`'s place, so you just need to switch their places. Because right now the bigger hive is first and it would be better if the smaller would come first in the list and after that the bigger hive.

**Comment by Nkiriobasi** [comment]
Hey, sorry please reassign this to someone else. Thank you.

**Comment by nikohoffren** [comment]
> Hey, sorry please reassign this to someone else. Thank you.

Sure, no worries!
