### ISSUE TITLE
Switch product placement in Products.tsx

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/hunajaholisti-website#37]
In Products.tsx, the `Big adopt a Hive` product has to be in `Small adopt a Hive`'s place, so their places need to be switched around. Because right now the bigger hive is first, and it would be better if the smaller would come first in the list and after that the bigger hive.

**Comment by vktr-r2** [comment]
Can I work on this?

**Comment by nikohoffren** [comment]
> Can I work on this?

Sure, go ahead! Feel free to ask any questions here if you have some problems.
