### ISSUE TITLE
Product Component

### ISSUE THREAD

**Issue by vasfvitor** [nikohoffren/hunajaholisti-website#38]
I managed more or less to create a product component, actually three, for _MessageUs_, _AddToCart_ and _Soon_ situations.

https://github.com/nikohoffren/hunajaholisti-website/compare/main...vasfvitor:hunajaholisti-website:product-component-no-iter

Main issue is that I don't know if changing `CartContext` from Products.tsx to ProductsCard.tsx will affect the cart or overall perfomance, and if that's the case how is the proper way to use it as a prop. In my implementation each `ProductAddToCart` component call `const { dispatch } = useContext(CartContext);` and for me it seems unnecessary.

On the other hand there's the image tag that I'm having trouble making it into the component. Mainly because I don't know what to do with `{isLoading && <Spinner />}` and `onLoad={() => imageLoaded()}`. 

In both cases the problem is really my lack of knowledge. I started React a few days ago and still getting a grip.

It's worth to mention that the current branch in the previous link is almost 1:1 visually, there's a tiny margin difference cause instead of `<br>` I used a `<p>` tag in the card description. The cart seems to work just fine.
left is original and right is my branch:
![image](https://github.com/nikohoffren/hunajaholisti-website/assets/61759797/a5b548d6-f48b-4610-aea4-bbae5d8eb037)

Does anyone have a suggestion to improve and how to approach those situations?

**Comment by nikohoffren** [comment]
> I managed more or less to create a product component, actually three, for _MessageUs_, _AddToCart_ and _Soon_ situations.
> 
> [main...vasfvitor:hunajaholisti-website:product-component-no-iter](https://github.com/nikohoffren/hunajaholisti-website/compare/main...vasfvitor:hunajaholisti-website:product-component-no-iter)
> 
> Main issue is that I don't know if changing `CartContext` from Products.tsx to ProductsCard.tsx will affect the cart or overall perfomance, and if that's the case how is the proper way to use it as a prop. In my implementation each `ProductAddToCart` component call `const { dispatch } = useContext(CartContext);` and for me it seems unnecessary.
> 
> On the other hand there's the image tag that I'm having trouble making it into the component. Mainly because I don't know what to do with `{isLoading && <Spinner />}` and `onLoad={() => imageLoaded()}`.
> 
> In both cases the problem is really my lack of knowledge. I started React a few days ago and still getting a grip.
> 
> It's worth to mention that the current branch in the previous link is almost 1:1 visually, there's a tiny margin difference cause instead of `<br>` I used a `<p>` tag in the card description. The cart seems to work just fine. left is original and right is my branch: ![image](https://user-images.githubusercontent.com/61759797/261177019-a5b548d6-f48b-4610-aea4-bbae5d8eb037.png)
> 
> Does anyone have a suggestion to improve and how to approach those situations?

I think your code at first glance looks mostly fine but the way the loading Spinner works, is that you can just move it just before the actual component that is rendered like this:

```typescript
{ isLoading && <Spinner /> }
<ProductMessageUs
    product={productByName["Honey350"]}
    lang={language}
    image={
        <img
            className="w-full h-48 object-cover"
            src={productByName["Honey350"].image}
            alt={
                language === "fi"
                    ? productByName["Honey350"].fi.alt
                    : productByName["Honey350"].en.alt
            }
            onLoad={() => imageLoaded()}
        />
    }
/>
```

That should make it to show the Spinner if the status is `isLoading`. After the image is loaded, it will show the actual image and get rid of the Spinner component. 

I checked the actual website with these changes with Netlify preview deploys and the cart and everything else seems to be working. I wouldn't worry too much about performance, i think it is fine for now, maybe it could be addressed in the future by creating new issue or pull request out of it.

**Comment by vasfvitor** [comment]
the spinner is supposed to be global or unique to each image loading? 
In the live version I made a simple test and the first image that load stops the spinner on all images.

In the dev branch I did the same test and each image has its own spinner and if the image doesn't load it will hang forever spinning for that image. To illustrate:
![image](https://github.com/nikohoffren/hunajaholisti-website/assets/61759797/6eb4956f-b317-4e63-84b4-367bb46818d8)
Of course, that should never happen. Just to consider.

latest commit: https://github.com/nikohoffren/hunajaholisti-website/commit/3daecb9dd20e1afd842e326f0359f62c4095515f

**Comment by nikohoffren** [comment]
> the spinner is supposed to be global or unique to each image loading? In the live version I made a simple test and the first image that load stops the spinner on all images.
> 
> In the dev branch I did the same test and each image has its own spinner and if the image doesn't load it will hang forever spinning for that image. To illustrate: ![image](https://user-images.githubusercontent.com/61759797/261395980-6eb4956f-b317-4e63-84b4-367bb46818d8.png) Of course, that should never happen. Just to consider.
> 
> latest commit: [3daecb9](https://github.com/nikohoffren/hunajaholisti-website/commit/3daecb9dd20e1afd842e326f0359f62c4095515f)

In the current live version all of the Spinners stop if only one of the images is loaded, which is not good but it works for now. I can always make smaller sizes of images for the products as right now most of them are too big. If we just get the images to show up in the cart as in original issue, that's the main thing.
